# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: slm.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='slm.proto',
  package='slm',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tslm.proto\x12\x03slm\"\x8b\x01\n\x10ImageDescription\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\x35\n\x0b\x63olour_type\x18\x03 \x01(\x0e\x32 .slm.ImageDescription.ColourType\"!\n\nColourType\x12\t\n\x05GREY8\x10\x00\x12\x08\n\x04RGB8\x10\x01\"X\n\tImageData\x12,\n\x0b\x64\x65scription\x18\x0b \x01(\x0b\x32\x15.slm.ImageDescriptionH\x00\x12\x0e\n\x04\x64\x61ta\x18\x04 \x01(\x0cH\x00\x42\r\n\x0bimage_oneof\"\"\n\x0bScreenReply\x12\x13\n\x0bnum_screens\x18\x05 \x01(\x05\"\x18\n\x06Screen\x12\x0e\n\x06screen\x18\x06 \x01(\x05\" \n\x08Position\x12\t\n\x01x\x18\x07 \x01(\x05\x12\t\n\x01y\x18\x08 \x01(\x05\"\r\n\x0b\x45mptyParams\",\n\x08Response\x12\x11\n\tcompleted\x18\t \x01(\x08\x12\r\n\x05\x65rror\x18\n \x01(\t2\x8e\x01\n\x03SLM\x12-\n\x08SetImage\x12\x0e.slm.ImageData\x1a\r.slm.Response\"\x00(\x01\x12)\n\tSetScreen\x12\x0b.slm.Screen\x1a\r.slm.Response\"\x00\x12-\n\x0bSetPosition\x12\r.slm.Position\x1a\r.slm.Response\"\x00\x62\x06proto3'
)



_IMAGEDESCRIPTION_COLOURTYPE = _descriptor.EnumDescriptor(
  name='ColourType',
  full_name='slm.ImageDescription.ColourType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GREY8', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RGB8', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=125,
  serialized_end=158,
)
_sym_db.RegisterEnumDescriptor(_IMAGEDESCRIPTION_COLOURTYPE)


_IMAGEDESCRIPTION = _descriptor.Descriptor(
  name='ImageDescription',
  full_name='slm.ImageDescription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='slm.ImageDescription.width', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='slm.ImageDescription.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='colour_type', full_name='slm.ImageDescription.colour_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _IMAGEDESCRIPTION_COLOURTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=158,
)


_IMAGEDATA = _descriptor.Descriptor(
  name='ImageData',
  full_name='slm.ImageData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='slm.ImageData.description', index=0,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='slm.ImageData.data', index=1,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='image_oneof', full_name='slm.ImageData.image_oneof',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=160,
  serialized_end=248,
)


_SCREENREPLY = _descriptor.Descriptor(
  name='ScreenReply',
  full_name='slm.ScreenReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_screens', full_name='slm.ScreenReply.num_screens', index=0,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=250,
  serialized_end=284,
)


_SCREEN = _descriptor.Descriptor(
  name='Screen',
  full_name='slm.Screen',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='screen', full_name='slm.Screen.screen', index=0,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=310,
)


_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='slm.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='slm.Position.x', index=0,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='slm.Position.y', index=1,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=344,
)


_EMPTYPARAMS = _descriptor.Descriptor(
  name='EmptyParams',
  full_name='slm.EmptyParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=346,
  serialized_end=359,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='slm.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='completed', full_name='slm.Response.completed', index=0,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='slm.Response.error', index=1,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=405,
)

_IMAGEDESCRIPTION.fields_by_name['colour_type'].enum_type = _IMAGEDESCRIPTION_COLOURTYPE
_IMAGEDESCRIPTION_COLOURTYPE.containing_type = _IMAGEDESCRIPTION
_IMAGEDATA.fields_by_name['description'].message_type = _IMAGEDESCRIPTION
_IMAGEDATA.oneofs_by_name['image_oneof'].fields.append(
  _IMAGEDATA.fields_by_name['description'])
_IMAGEDATA.fields_by_name['description'].containing_oneof = _IMAGEDATA.oneofs_by_name['image_oneof']
_IMAGEDATA.oneofs_by_name['image_oneof'].fields.append(
  _IMAGEDATA.fields_by_name['data'])
_IMAGEDATA.fields_by_name['data'].containing_oneof = _IMAGEDATA.oneofs_by_name['image_oneof']
DESCRIPTOR.message_types_by_name['ImageDescription'] = _IMAGEDESCRIPTION
DESCRIPTOR.message_types_by_name['ImageData'] = _IMAGEDATA
DESCRIPTOR.message_types_by_name['ScreenReply'] = _SCREENREPLY
DESCRIPTOR.message_types_by_name['Screen'] = _SCREEN
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
DESCRIPTOR.message_types_by_name['EmptyParams'] = _EMPTYPARAMS
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageDescription = _reflection.GeneratedProtocolMessageType('ImageDescription', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEDESCRIPTION,
  '__module__' : 'slm_pb2'
  # @@protoc_insertion_point(class_scope:slm.ImageDescription)
  })
_sym_db.RegisterMessage(ImageDescription)

ImageData = _reflection.GeneratedProtocolMessageType('ImageData', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEDATA,
  '__module__' : 'slm_pb2'
  # @@protoc_insertion_point(class_scope:slm.ImageData)
  })
_sym_db.RegisterMessage(ImageData)

ScreenReply = _reflection.GeneratedProtocolMessageType('ScreenReply', (_message.Message,), {
  'DESCRIPTOR' : _SCREENREPLY,
  '__module__' : 'slm_pb2'
  # @@protoc_insertion_point(class_scope:slm.ScreenReply)
  })
_sym_db.RegisterMessage(ScreenReply)

Screen = _reflection.GeneratedProtocolMessageType('Screen', (_message.Message,), {
  'DESCRIPTOR' : _SCREEN,
  '__module__' : 'slm_pb2'
  # @@protoc_insertion_point(class_scope:slm.Screen)
  })
_sym_db.RegisterMessage(Screen)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), {
  'DESCRIPTOR' : _POSITION,
  '__module__' : 'slm_pb2'
  # @@protoc_insertion_point(class_scope:slm.Position)
  })
_sym_db.RegisterMessage(Position)

EmptyParams = _reflection.GeneratedProtocolMessageType('EmptyParams', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYPARAMS,
  '__module__' : 'slm_pb2'
  # @@protoc_insertion_point(class_scope:slm.EmptyParams)
  })
_sym_db.RegisterMessage(EmptyParams)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'slm_pb2'
  # @@protoc_insertion_point(class_scope:slm.Response)
  })
_sym_db.RegisterMessage(Response)



_SLM = _descriptor.ServiceDescriptor(
  name='SLM',
  full_name='slm.SLM',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=408,
  serialized_end=550,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetImage',
    full_name='slm.SLM.SetImage',
    index=0,
    containing_service=None,
    input_type=_IMAGEDATA,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetScreen',
    full_name='slm.SLM.SetScreen',
    index=1,
    containing_service=None,
    input_type=_SCREEN,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetPosition',
    full_name='slm.SLM.SetPosition',
    index=2,
    containing_service=None,
    input_type=_POSITION,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SLM)

DESCRIPTOR.services_by_name['SLM'] = _SLM

# @@protoc_insertion_point(module_scope)
