# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rusty_slm/slm.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13rusty_slm/slm.proto\x12\x03slm\"\x8b\x01\n\x10ImageDescription\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\x35\n\x0b\x63olour_type\x18\x03 \x01(\x0e\x32 .slm.ImageDescription.ColourType\"!\n\nColourType\x12\t\n\x05GREY8\x10\x00\x12\x08\n\x04RGB8\x10\x01\"X\n\tImageData\x12,\n\x0b\x64\x65scription\x18\x0b \x01(\x0b\x32\x15.slm.ImageDescriptionH\x00\x12\x0e\n\x04\x64\x61ta\x18\x04 \x01(\x0cH\x00\x42\r\n\x0bimage_oneof\"\"\n\x0bScreenReply\x12\x13\n\x0bnum_screens\x18\x05 \x01(\x05\"\x18\n\x06Screen\x12\x0e\n\x06screen\x18\x06 \x01(\x05\" \n\x08Position\x12\t\n\x01x\x18\x07 \x01(\x05\x12\t\n\x01y\x18\x08 \x01(\x05\"\r\n\x0b\x45mptyParams\",\n\x08Response\x12\x11\n\tcompleted\x18\t \x01(\x08\x12\r\n\x05\x65rror\x18\n \x01(\t2\x8e\x01\n\x03SLM\x12-\n\x08SetImage\x12\x0e.slm.ImageData\x1a\r.slm.Response\"\x00(\x01\x12)\n\tSetScreen\x12\x0b.slm.Screen\x1a\r.slm.Response\"\x00\x12-\n\x0bSetPosition\x12\r.slm.Position\x1a\r.slm.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rusty_slm.slm_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGEDESCRIPTION._serialized_start=29
  _IMAGEDESCRIPTION._serialized_end=168
  _IMAGEDESCRIPTION_COLOURTYPE._serialized_start=135
  _IMAGEDESCRIPTION_COLOURTYPE._serialized_end=168
  _IMAGEDATA._serialized_start=170
  _IMAGEDATA._serialized_end=258
  _SCREENREPLY._serialized_start=260
  _SCREENREPLY._serialized_end=294
  _SCREEN._serialized_start=296
  _SCREEN._serialized_end=320
  _POSITION._serialized_start=322
  _POSITION._serialized_end=354
  _EMPTYPARAMS._serialized_start=356
  _EMPTYPARAMS._serialized_end=369
  _RESPONSE._serialized_start=371
  _RESPONSE._serialized_end=415
  _SLM._serialized_start=418
  _SLM._serialized_end=560
# @@protoc_insertion_point(module_scope)
